// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'coin.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$CoinImpl _$$CoinImplFromJson(Map<String, dynamic> json) => _$CoinImpl(
      createdAt: json['createdAt'] as String?,
      description: json['description'] as String?,
      enName: json['enName'] as String?,
      ext: json['ext'] as String?,
      fullName: json['fullName'] as String?,
      id: (json['id'] as num?)?.toInt(),
      isAutoTrans: json['isAutoTrans'] as bool?,
      isAutoWithdraw: json['isAutoWithdraw'] as bool?,
      isRecharge: json['isRecharge'] as bool?,
      isTrans: json['isTrans'] as bool?,
      isWithdraw: json['isWithdraw'] as bool?,
      maxWithdraw: (json['maxWithdraw'] as num?)?.toDouble(),
      maxWithdrawFee: (json['maxWithdrawFee'] as num?)?.toDouble(),
      minRecharge: (json['minRecharge'] as num?)?.toDouble(),
      minWithdraw: (json['minWithdraw'] as num?)?.toDouble(),
      minWithdrawFee: (json['minWithdrawFee'] as num?)?.toDouble(),
      name: json['name'] as String?,
      price: (json['price'] as num?)?.toDouble(),
      priceType: json['priceType'] as bool?,
      protocol: (json['protocol'] as num?)?.toInt(),
      rechargeInfo: json['rechargeInfo'] as String?,
      sort: (json['sort'] as num?)?.toInt(),
      state: json['state'] as bool?,
      transFee: (json['transFee'] as num?)?.toDouble(),
      transFeeType: json['transFeeType'] as bool?,
      transInfo: json['transInfo'] as String?,
      transMax: (json['transMax'] as num?)?.toDouble(),
      transMaxFee: (json['transMaxFee'] as num?)?.toDouble(),
      transMin: (json['transMin'] as num?)?.toDouble(),
      transMinFee: (json['transMinFee'] as num?)?.toDouble(),
      transRate: (json['transRate'] as num?)?.toDouble(),
      updatedAt: json['updatedAt'] as String?,
      withdrawFee: (json['withdrawFee'] as num?)?.toDouble(),
      withdrawFeeType: json['withdrawFeeType'] as bool?,
      withdrawInfo: json['withdrawInfo'] as String?,
      withdrawRate: (json['withdrawRate'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$$CoinImplToJson(_$CoinImpl instance) =>
    <String, dynamic>{
      'createdAt': instance.createdAt,
      'description': instance.description,
      'enName': instance.enName,
      'ext': instance.ext,
      'fullName': instance.fullName,
      'id': instance.id,
      'isAutoTrans': instance.isAutoTrans,
      'isAutoWithdraw': instance.isAutoWithdraw,
      'isRecharge': instance.isRecharge,
      'isTrans': instance.isTrans,
      'isWithdraw': instance.isWithdraw,
      'maxWithdraw': instance.maxWithdraw,
      'maxWithdrawFee': instance.maxWithdrawFee,
      'minRecharge': instance.minRecharge,
      'minWithdraw': instance.minWithdraw,
      'minWithdrawFee': instance.minWithdrawFee,
      'name': instance.name,
      'price': instance.price,
      'priceType': instance.priceType,
      'protocol': instance.protocol,
      'rechargeInfo': instance.rechargeInfo,
      'sort': instance.sort,
      'state': instance.state,
      'transFee': instance.transFee,
      'transFeeType': instance.transFeeType,
      'transInfo': instance.transInfo,
      'transMax': instance.transMax,
      'transMaxFee': instance.transMaxFee,
      'transMin': instance.transMin,
      'transMinFee': instance.transMinFee,
      'transRate': instance.transRate,
      'updatedAt': instance.updatedAt,
      'withdrawFee': instance.withdrawFee,
      'withdrawFeeType': instance.withdrawFeeType,
      'withdrawInfo': instance.withdrawInfo,
      'withdrawRate': instance.withdrawRate,
    };
