Map<String, String> en_US = {
  //首页
  '可用余额': 'Available Balance',
  '冻结中': 'For sale',
  '交易中': 'In Progress',
  '买币': 'Coin purchase',
  '卖币': 'Coin selling',
  '收款账户': 'Account',
  '订单中心': 'Order',
  '账单记录': 'Bill',
  '我的团队': 'Team',
  '帮助中心': 'Help',
  '代币充值': 'Recharge',
  '热门币种': 'Popular Coins',
  '上升': 'Up',
  '下降': 'Fall',
  '首页': 'Home',
  '我的': 'Me',

  'Dear user: Thank you for using Gopay wallet. Please follow our working hours: Monday to Sunday AM10:30-PM10:30':
      'Dear user: Thank you for using Gopay wallet. Please follow our working hours: Monday to Sunday AM10:30-PM10:30',
  '合作': 'cooperation',
  '交易下限': 'Down',
  '交易上限': 'Up',
  '支付方式': 'payment',
  '1万': 'ten thousand',
  '10万': 'hundred thousand',
  '20万': 'two hundred thousand.',
  '例如 100': 'For example 100',
  '重置': 'Reset',
  '确认': 'Confirm',
  '成单量': 'uniformization',
  '成单率': 'Order making rate',
  '分钟': 'minutes',
  '剩余金额 ': 'Residual amount ',
  '限额 ': 'quota ',
  '购买': 'Buy',
  '出售': 'Sell',
  '确认订单': 'Confirm order',
  '付款时限': 'Payment deadline',
  '限制额度': 'Limitation amount',
  '交易方式': 'Trading method',
  '请输入金额': 'Please enter the amount',
  '金额': 'Amount',
  '总额': 'Gross amount',
  '买家留言': 'Buyer\'s message',
  '卖家留言': 'Seller message',
  '付款信息': 'Payment information',
  '未识别': 'Unrecognized',
  '交易须知': 'Trading instructions',
  'tradeTerms':
      '1. When the order is generated, please complete the transfer and upload the transaction voucher \n2 within 10 minutes. Please use the binding payment method to pay, if the payment information does not match the seller has the right not to release \n3. Please do not maliciously initiate the purchase order, after verification of the permanent block processing. 4. If you can not pay, transaction disputes, click the customer service button above.',
  '温馨提示': 'Warm reminder',
  '为保证资金安全，我们将随机小数点后两位，请按照具体金额进行支付':
      'In order to ensure the security of the funds, we will randomly place two decimal places, please pay according to the specific amount',

  '输入密码支付': 'Enter Pin to Pay',
  '为了安全起见，请输入您的交易密码以继续交易':
      'To continue transaction, please enter your transaction PIN for security reason',
  '输入密码': 'Enter Pin',
  '等待卖家确认': 'Wait for seller confirmation',
  '已通知，等待卖家确认订单': 'Notification received, waiting for seller to confirm order',
  '剩余时间 ': 'Remaining time ',
  '订单号': 'Order Number',
  '总金额': 'Total amount',
  '备注码': 'Remark code',
  '卖家信息': 'Seller Information',
  '取消订单': 'Cancel order',
  '通知卖家': 'Notification to seller',
  '通知买家': 'Notification to buyer',
  '催单': 'Remind',
  '收款方式': 'Payment method',
  '收款二维码': 'Receipt QR code',
  '有过合作用户': 'Have cooperated with users',
  '收款通道': 'Payment channel',
  '添加收款方式': 'Add payment method',
  '异常': 'Abnormal',
  '开启': 'Enable',
  '关闭': 'Disable',
  '账号': 'Account',
  '姓名': 'Name',
  '银行卡号': 'Bank card number',
  '收款地址类型': 'Payment address type',
  '收款地址': 'Payment address',
  '收款码': 'Payment code',
  '您暂时无法接受订单，请先添加一个收款方式':
      'You cannot accept orders at this time, please add a payment method first',
  '删除': 'Delete',
  '请输入你的昵称': 'Please enter your nickname',

  '收款状态': 'Payment status',
  '钱包地址协议': 'Wallet address protocol',
  '请选择钱包地址协议': 'Please select the wallet address protocol',
  '钱包地址': 'Wallet address',
  '请输入钱包地址': 'Please enter the wallet address',
  '请输入账号': 'Please enter your account number',
  '开户行': 'Bank',
  '请输入开户行 (XXX银行XXX市XXX支行)':
      'Please enter the bank (XXX bank XXX city XXX branch)',
  '收款人姓名': 'Name of the account holder',
  '请输入收款人姓名': 'Please enter the name of the account holder',
  '上传二维码': 'Upload QR code',
  '请选择包含二维码图片': 'Please select a picture containing a QR code',
  '温馨提醒:': 'Warm reminder:',
  '点击此处上传您的': 'Click here to upload yours',
  '收付款二维码，您可以使用此二维码进行买卖':
      'Receipt and payment QR code, you can use this QR code to buy and sell',
  '保存': 'Save',
  '发布选择': 'Publish selection',
  '我的挂单': 'Pending order',
  '我的订单': 'My order',
  '订单管理': 'Order management',
  '挂单记录': 'Pending order record',
  '全部': 'All',
  '买入': 'Purchase',
  '卖出': 'Sale',
  '已完成': 'Completed',
  '已取消': 'Canceled',
  '已终止': 'Terminated',

  '确认终止挂单吗?': 'Are you sure to terminate the order?',
  '终止挂单': 'Terminate order',
  '收款类型': 'Collection type',
  '数量': 'Quantity',
  '剩余数量': 'Remaining quantity',
  '单次购买上限': 'Single purchase upper limit',
  '单次购买下限': 'Single purchase lower limit',
  '申诉中': 'Appealing',
  '订单已取消': 'Order has been canceled ',
  '等待卖家确认收款': 'Wait for the seller to confirm the payment',
  '我的购买': 'My purchase',
  '我的出售': 'My sale',
  '等待买家确认付款': 'Wait for buyer to  payment',
  '收款信息': 'Collection information',
  '如收到款项与交易金额一致，请立即点击我已确认收款， 切勿相信短信到账提示，请已官方App或网银实时为主！':
      'Tips: If the payment received is consistent with the transaction amount, please click Me to confirm the payment immediately, do not believe the SMS to the account prompt, please have the official App or online bank real-time main!',
  '此卖家95%的订单将会在7分钟内完成':
      '95% of this seller\'s orders will be completed within 7 minutes',
  '卖家收款方式': 'Seller payment method',
  '付款凭证': 'Payment credentials',
  '请确认已收到款': 'confirm receipt of payment',
  '将确认收款': 'Collection will be confirmed',
  '登录下方收款账号确认收款到账': 'Login to the account below to confirm receipt',
  '如若未收到款或收款金额与交易金额不符，请在倒计时结束前点击未收到款！':
      'If the payment is not received or the amount received is not consistent with the transaction amount, please click on the payment not received before the countdown ends!',
  '未收到款': 'Unreceived',
  '我已确认收款': 'I have confirmed receipt',
  '买入成功': 'Successful purchase',
  '卖出成功': 'Successful sale',
  '创建时间': 'Creation Time',
  '完成': 'Confirm',

  '申诉': 'Appeal',
  '撤销申诉': 'Cancel appeal',
  '申诉原因': 'Reason for appeal',
  '申诉内容': 'Content of appeal',
  '输入申诉内容': 'Enter appeal content',
  '申诉内容(可选择)': 'Content of appeal (optional)',
  '添加交易截图': 'Add trade screenshot',
  '添加交易录屏 (可选)': 'Add trade recording (optional)',
  '请选择申诉原因': 'Please select the reason for the appeal',
  '确定取消吗': 'Are you sure you want to cancel?',

  '实名认证': 'Real-name authentication',
  '添加收付款': 'Add collection and payment',

  '第一步：进入实名认证': 'Step 1: Enter real-name authentication',
  '第二步：输入身份证信息': 'Step 2: Enter ID card information',
  '第一步：进入市场购买': 'Step 1: Enter the market to purchase',
  '在首页，点击购买按钮，进入市场':
      'On the homepage, click the buy button to enter the market',
  '第二步：市场购买': 'Step 2: Market purchase',
  '选择买家后，输入需要购买金额并选择付款方式':
      'After selecting the buyer, enter the purchase amount and choose the payment method',
  '第三步：等待卖家确认': 'Step 3: Wait for the seller to confirm',
  '第一步：进入市场出售': 'Step 1: Enter the market to sell',
  '在首页，点击出售按钮，进入市场':
      'On the homepage, click the sell button to enter the market',
  '第二步：市场出售': 'Step 2: Market sale',
  '选择买家后，输入需要出售金额并选择付款方式':
      'After selecting the buyer, enter the amount to sell and choose the payment method',
  '第三步：等待买家确认': 'Step 3: Wait for the buyer to confirm',
  '验证码验证错误': 'CAPTCHA verification error',
  'error': 'error',

  '您已成功购买 num coinName': 'You have bought :num :coinName',
  '您已成功出售 num coinName': 'You have sold :num :coinName',
  '订单信息': 'Order Information',
  '卖家昵称': 'Seller nickname',
  '买家昵称': 'Buyer nickname',
  '进行中': 'Under way',
  '请选择日期区间': 'Please select a date range',
  '取消': 'Cancel',
  '确定': 'Confirm',
  '选择时间': 'Select time',
  '记录为空': 'Record is empty',
  '余额': 'Balance',
  '时间': 'Time',
  '今日收益': 'Today\'s benefits',
  '昨日收益': 'Yesterday\'s benefits',
  '累计收益': 'Cumulative benefits',
  '直接邀请': 'Direct Invite',
  '间接邀请': 'Indirect Invite',
  '我的代理': 'My agent',
  '转账': 'Transfer',
  '直邀': 'Direct Invite',
  '间邀': 'Indirect Invite',
  '今日贡献': 'Today',
  '昨日贡献': 'Yesterday',
  '累计贡献': 'Cumulative',
  '佣金金额': 'Commission amount',
  '成功': 'succeed',

  '团队用户': 'Team Users',
  '代理管理': 'Agency management',
  '佣金比例': 'Commission rate',
  '代付佣金比例': 'Commission rate for collection',
  '代收佣金比例': 'Commission rate for payment',
  '修改佣金比例': 'Modify commission rate',
  '修改后立即生效，只可更改一次。请谨慎处理。':
      'The modified commission rate will take effect immediately, and can only be changed once. Please handle with caution.',
  '请输入佣金比例': 'Please enter the commission rate',
  '充值': 'Recharge',
  '充值明细': 'Details',
  '选择公链协议': 'Select public chain protocol',
  '区块链浏览器': 'Blockchain Browser',
  'chargeTip':
      'The current address can only be charged to USDT, and the main network public chain is the :chainType protocol, and cannot be recharged to other currencies, otherwise it will be lost and cannot be recovered.',
  '提交': 'Submit',
  '加载地址失败': 'Failed to load address',
  '预估': 'Estimated ',
  '您的购买地址': 'Your purchase address',
  '复制成功': 'Copied successfully',
  '需支付金额（USDT）': 'Amount payable (USDT)',
  '保存成功': 'Saved successfully',
  '分享': 'Share',
  '充值金额': 'recharge amount',
  '充值详情': 'Recharge details',
  '您正在充值': 'You are topping up',
  '您已经成功充值': 'You have successfully topped up your account',
  '充值时间': 'Recharge time',
  '充币公链协议': 'Full coin public chain protocol',
  '实际支付': 'actual payment',
  '交易HASH': 'Transaction HASH',
  '充值失败': 'Recharge failure',
  '失败': 'Failed',
  '查看全部': 'View All',
  '添加成功': 'Successfully added',
  '修改成功': 'Modify successfully',

  '支付': 'Pay',
  '未知': 'unknown',
  '购买金额': 'Purchase Amount',
  '请输入购买金额': "Please enter the purchase amount",
  '请输入最大金额': 'Please enter the maximum amount',
  '备注': 'Note',
  '请输入您要留下的备注': 'Please enter your note',
  '付款类型': 'Payment type',
  '请选择付款类型': 'Please select the payment type',
  '您确认要发布该广告嘛': 'You\'re sure you want to publish the AD',
  '发布订单': 'Place an order',
  '收款渠道': 'Collection channel',
  '付款渠道': 'Payment channel',
  '确认渠道': 'Confirm channel',
  '发布卖出': 'Publish sell',
  '卖出金额': 'Selling amount',
  '请输入卖出金额': 'Please enter the selling amount',
  '单次卖出上限': 'Single selling upper limit',
  '单次卖出下限': 'Single sell floor',
  '请输入最小金额': 'Please enter the minimum amount',
  '确定退出': 'Definite exit',
  '您确定要退出登录吗?': 'Are you sure you want to log out?',
  '退出': 'Quit',
  '设置': 'Settings',
  '账号绑定': 'Account binding',
  '语言': 'Language',
  '提现': 'Withdraw',
  '密码与安全': 'Password and security',
  '交易密码': 'Transaction pin',
  '登录密码': 'Login password',
  '其他': 'Other',
  '分享有礼': 'Share Gifts',
  'uploading': 'uploading',
  '用户须知': 'User agreement',
  '邀请码': 'Invitation Code',
  '邀请码（选填）': 'Invitation Code（optional）',
  '当前版本': 'Current Version',
  '个人信息': 'Personal details',
  '设置用户昵称': 'Set user nickname',
  '手机号绑定': 'Mobile phone number binding',
  '未绑定': 'Unbound',
  '邮箱绑定': 'Mailbox binding',
  '输入您的手机号': 'Enter your phone number',
  '输入您的邮箱': 'Enter your email address',
  '验证码': 'CAPTCHA',
  '获取验证码': 'Get CAPTCHA',

  '重新获取': 'Resend',
  '请输入验证码': 'Please enter the CAPTCHA',
  '明细': 'Details',
  '请输入收款地址': 'Please enter the collection address',
  '提现金额': 'cash withdrawal amount',
  '请输入提现金额': 'Please enter the withdrawal amount',
  '手续费': 'Handling fee',
  '将收到': 'You will receive',
  '您确认要提现吗': 'Are you sure you want to withdraw cash',
  '确定提现': 'Definite withdrawal',
  '请输入交易密码': 'Please enter your trading password',
  '提现明细': 'Withdrawal details',
  '状态': 'Status',
  '未处理': 'Untreated',
  '已通过': 'Passed',
  '已拒绝': 'Rejected',
  '请输入当前密码': 'Please enter current password',
  '密码输入': 'Password input',
  '请输入新密码': 'Please enter new password',
  '再次输入新密码': 'Enter the new password again',
  '您想要修改密码吗？': 'Do you want to change your password?',
  '保存图片': 'Save picture',
  '您的收款地址:': 'Your collection address:',
  '转账记录': 'Transfer record',
  '您的转账地址': 'Your transfer address',
  '输入或粘贴地址': 'Enter or paste the address',
  '转账金额': 'Transfer amount',
  '实际到账': 'Actual arrival',
  '记录': 'Record',
  '收款': 'Gathering',
  '转账地址': 'Transfer address',
  '需要操作': 'Action required',
  '待确认': 'Be Confirmed',
  '确认收款': 'confirmed receipt',
  '如果你未收到订单的现金。请不要确认订单，否则资金损失，我们不予负责':
      'If you have not received the cash for the order. Please do not confirm the order, otherwise we will not be responsible for any financial losses',
  '欢迎回来': 'welcome to',
  'Log in to your account': 'Log in to your account',
  '创建账户': 'Create an account',
  'welcome': 'welcome',
  'to': 'to',
  '已有账户': 'Existing account',
  '接收验证码': 'Receive CAPTCHA',

  '密码登录': 'Password login',
  '没有帐号？': 'No account?',
  '前去注册': 'pre-register',
  '找回方式': 'Retrieval mode',
  '邮箱找回': 'Email retrieval',
  '手机号找回': 'Phone number retrieval',
  '请输入帐号': 'Please enter your account number',
  '请输入您的密码': 'please enter your PIN',
  '二次确认密码': 'Double confirmation password',
  '再次输入密码': 'Reenter password',
  '请输入正确的手机号或邮箱': 'Please enter the correct phone number or email address',
  '请输入收到的验证码': 'Please enter the verification code you received',
  '请输入设置的密码': 'Please enter your password',
  '请输入确认密码': 'Please enter your confirmation password',
  '两次输入的密码不一致，请重新输入': 'The two passwords are different. Please re-enter them',
  '让我们开始吧！': 'Let\'s start',
  '现在就注册!': 'sign up now',
  '输入用户昵称': 'Enter user nickname',
  '已有帐户？': 'have an account?',
  '身份认证已通过': 'The identity authentication has passed',
  '您的收款二维码': 'Your payment QR code',
  '确认收款吗?': 'Do you confirm the payment?',
  '发布成功': 'Release success',
  '此卖家95%订单会在7:00处理': '95% of this seller\'s orders are processed at 7:00',
  '添加付款凭证': 'Add payment voucher',
  '添加付款凭证录屏（可选）': 'Add payment voucher screen recording (optional)',
  '请添加付款凭证': 'Please add the payment voucher',

  '凌晨': 'Early morning',
  '早晨': 'Morning',
  '上午': 'Forenoon',
  '中午': 'Noon',
  '下午': 'Afternoon',
  '傍晚': 'Evening',
  '晚上': 'Night',

  '年': 'Year',
  '月': 'Month',
  '日': 'Day',

////暂时不用

  '当前汇率': 'Current Exchange Rate',

  '交易': 'Trade',
  '承兑': 'Accept',
  '商户': 'Merchant',

  //我的
  '身份认证': 'Authentication',
  '收款管理': 'Payment Management',
  '历史订单': 'History Orders',
  '谷歌验证': 'Google Verification',
  '关于我们': 'About Us',
  '在线客服': 'Online Customer Service',
  //交易
  '更多': 'more',
  '匹配中': 'Matching',

  '暂无订单信息～': 'No order information yet～',
  //other
  '通知': 'Notification',
  '当前通话已被加密': 'The current call has been encrypted',
  '客服': 'Customer Service',
  '相册': 'Album',
  '公链协议（即网络协议）': 'Public chain protocol (network protocol)',
  '请输入您要购买的:coin数量': 'Please enter the number of :coin you want to purchase',

  '需支付': 'Need to pay ',
  '购买二维码': ':coinName Purchase QR code',
  '保存二维码': 'Save QR code',
  '请严格按照以上金额进行转账, 否则如果无法到账, 平台概不负责':
      'Please strictly follow the above amount for transfer, otherwise if it cannot arrive, the platform will not be responsible',
  '购买明细': 'Purchase Details',

  '支付USDT': 'Pay USDT',
  'coinName购买': ':coinName Purchase',
  '收益记录': 'Income Record',
  '今日': 'Today',
  '昨日': 'Yesterday',
  '进行中订单': 'In-progress Orders',
  '代收金额': 'Amount collected',
  '代付金额': 'Amount paid',
  '总收益': 'Total Income',
  '收益明细': 'Income Details',
  '请选择日期': 'Please select date',
  '收入': 'Income',
  '原订单号': 'Original Order Number',
  'shareTip1': 'Share new user completed :limit:coinName Coin transaction',
  'shareTip2': 'You can get the reward of :reward:coinName coins',
  '昵称': 'Nickname',
  '修改登录密码': 'Modify login password',
  '邮箱': 'Email',
  '未设置': 'Not set',
  '手机号': 'Mobile number',
  '资金密码': 'Fund password',
  '修改资金密码': 'Modify fund password',
  '退出登录': 'Logout',
  '确认退出吗?': 'Are you sure to logout?',
  '请输入昵称': 'Please enter your nickname',
  '5-12位字母或数字，请勿使用特殊符号':
      '5-12 characters, letters or numbers, please do not use special symbols',
  '旧密码': 'Old password',
  '请输入旧密码': 'Please enter your old password',
  '密码': 'Password',
  '请输入密码': 'Please enter your password',
  '确认密码': 'Confirm password',
  '开启手机验证': 'Enable mobile verification',
  '开启邮箱验证': 'Enable email verification',
  '为您的账户提供更安全的保护。': 'To provide a more secure protection for your account.',
  '请输入手机号': 'Please enter your mobile number',
  '请输入邮箱号': 'Please enter your email address',
  '下一步': 'Next step',
  '请输入正确的手机号码': 'Please enter a valid mobile number',
  '请输入正确的邮箱': 'Please enter a valid email address',
  '请输入发送至手机号 phone的6位验证码':
      'Please enter the 6-digit verification code sent to :phone',
  '重新获取(seconds秒)': 'Resend (:seconds seconds)',
  '手机': 'Mobile',
  '请输入6位纯数字密码': 'Please enter a 6-digit pure number password',
  '银行卡': 'Bank card',
  '支付宝': 'Alipay',
  '微信': 'Wechat',
  '尚未绑定手机号': 'Mobile number not yet bound',

  '微信账号': 'Wechat account',
  '请输入支付宝账号': 'Please enter your Alipay account',
  '请输入微信账号': 'Please enter your Wechat account',
  '请输入银行卡号': 'Please enter your bank card number',

  '每日最大接单金': 'Maximum daily order amount',
  '返回': 'Back',
  '全选': 'Select all',
  '等待买家确认': 'Waiting for the buyer to confirm',
  '待付款': 'Pending payment',
  '待确认收款': 'Pending confirmation of receipt',
  '查看详情': 'View details',
  '卖家收款二维码': 'Seller payment QR code',
  '我买入的': 'I bought',
  '我卖出的': 'I sold',
  '我的余额': 'My balance',
  '代理佣金': 'Agent commission',
  '请输入申诉的内容': 'Please enter the content of the appeal',
  '已通知，等待买家确认订单': 'Notified, waiting for the buyer to confirm the order',

  '确定申诉': 'Confirm appeal',

  '修改': 'Modify',
  '总价': 'Total price',
  '请输入两次密码不一致，请重新输入': 'The two passwords do not match, please re-enter',
  '请输入您的确认密码': 'Please enter your confirmation password',
  '请输入您的名字': 'Please enter your name',
  '请确认支付密码': 'Please confirm the payment password',
  '支付密码两次设置不一样': 'The payment password entered twice does not match',
  '请输入支付密码': 'Please enter the payment password',
  '请输入转账金额': 'Please enter the transfer amount',

  '收款记录': 'Payment Records',
  '请在手机上安装谷歌身份验证器': 'Please install Google Authenticator on your mobile phone',
  '复制密钥': 'Copy key',
  '二维码': 'QR code',
  '开启谷歌验证': 'Enable Google Verification',
  '请输入6位验证码': 'Please enter a 6-digit verification code',
  '谷歌验证身份': 'Google Verification Identity',
  '验证身份': 'Verify Identity',
  '请选择您要成为的身份': 'Please select the identity you want to become',
  '自动接单': 'Automatic order acceptance',
  '去完成': 'Go to complete',
  '商家': 'Merchant',
  '发布广告': 'Publish Advertisement',
  '认证': 'Authentication',
  '商户名称': 'Merchant Name',
  '请输入您的商户名称': 'Please enter your merchant name',
  '请输入您的昵称': 'Please enter your nickname',
  '请输入您的联系方式': 'Please enter your contact information',
  '地址链接': 'Address link',
  '请输入您的地址链接': 'Please enter your address link',
  '登录': 'Login',
  '注册': 'Sign up',
  '忘记密码': 'Forget password',
  '请输入邮箱': 'Please enter your email',
  '手机号码': 'Mobile number',
  '请选择国家/地区': 'Please select a country/region',
  '切换验证码登录': 'Switch to verification code login',
  '切换密码登录': 'Switch to password login',
  '“国家/地区”、“代码”或“拨号代码”': '"Country/region", "Code", or "Dialing code"',
  '请输入邀请码': 'Please enter the invitation code',
  '已有账号，去登录': 'Already have an account, go sign in',
  '重置密码': 'Reset password',
  '确认重置': 'Confirm reset',
  '发布买入': 'Publish buy',
  '今日购买上限': 'Today\'s purchase upper limit',
  '今日卖出上限': 'Today\'s selling upper limit',
  '请输入购买数量': 'Please enter the purchase quantity',

  '保存配置': 'Save configuration',
  '停止接单': 'Stop receiving',
  '开启接单': 'Start receiving',
  '卖出数量': 'Quantity sold',
  '请输入卖出数量': 'Please enter quantity sold',
  '您确认要出售吗': 'Are you sure to sell?',
  '确定出售': 'Confirm sale',
  '出售明细': 'Sale Details',
  '地址': 'Address',
  '预计将在time打款': 'The payment will be made in :time',

  '交易记录': 'Trade Records',
  '再按一次退出应用': 'Press again to exit the app',
  '提交成功!': 'Submitted successfully!',
  '联系客服': 'Contact customer service',
  '单价': 'Unit price',

  '银行借记卡': 'Bank debit card',
  '按金额卖出': 'Sell by amount',
  '按数量卖出': 'Sell by quantity',
  '按金额购买': 'Buy by amount',
  '按数量购买': 'Buy by quantity',
  '交易条款': 'Trading terms',

  '1.如果您已经付款给卖家，请勿取消订单':
      '1.If you have paid to the seller, please do not cancel the order',
  '2.如因系统超时订单取消，买家将被记责（完成率受影响）。':
      '2.If the order is cancelled due to system timeout, the buyer will be charged (the completion rate may be affected).',
  '3.如果卖家在15分钟内没有回复聊天，则买家无责，您的成单率将不受影响，一天内只能3次无责取消。':
      '3.If the seller does not reply within 15 minutes, the buyer is in no obligation, and your success rate will not be affected. You can only cancel 3 times in a day without any fault.',
  '4.一天内您最多只能3次有责取消，否则，您的账户将被暂停，并且不能再同一天内再下订单。':
      '4.You can only cancel 3 times in a day with fault, otherwise, your account will be suspended and you will not be able to place an order on the same day again.',
  '确认取消': 'Confirm cancellation',
  '请等待客服处理': 'Please wait for the customer service to process',
  '收款账号': 'Collection account',
  '充值至您的账户': 'Recharge to your account',
  '已经成功出售': 'You have sold successfully',

  '请确认已收到付款': 'Please confirm that you have received the payment',
  '后将自动确认收款': ' after that, the payment will be automatically confirmed',
  '登录您下方的收款账户，确认买家的付款已到账。':
      'Log in to your collection account below to confirm that the buyer\'s payment has arrived.',
  '买家实名': 'Buyer real name',
  '重要提示：如果未收到款或者收到款项与交易金额不符，请在倒计时结束前点击“未收到款”！':
      'Important Note: If you have not received payment or the amount of the payment does not match the transaction amount, please click "Unreceived" before the countdown ends!',
  '请使用paymentType支付转账': 'Please use :paymentType to transfer funds',
  '资金将划转至您的账户': 'Funds will be transferred to your account',
  '订单即将生成': 'Order is about to be generated',
  '预计将在': 'Estimated delivery time ',
  '自动取消': ' auto cancel',
  '我已付款': 'I have paid',
  '等待买家付款': 'Waiting for buyer to pay',
  '付款剩余时间：': 'Payment remaining time: ',
  '异常原因': 'Abnormal reason',
  '无法付款': 'Unable to pay',
  'Please complete': 'Please complete',
  "'authentication'": "'authentication'",
  'authentication': 'authentication',
  'auth': 'auth',
  'video auth': 'video auth',
  'Upload ID card photo': 'Upload ID card photo',
  'ID card is used to bind: transaction info':
      'ID card is used to bind: transaction info',
  'Identity information': 'Identity information',
  'Real name': 'Real name',
  'ID Number': 'ID Number',
  'standard': 'standard',
  'defect': 'defect',
  'vague': 'vague',
  'Strong light': 'Strong light',
  'Start certification': 'Start auth',
  'End certification': 'End auth',
  'light': 'light',
  'face': 'face',
  'No glasses': 'No glasses',
  'No hat': 'No hat',
  'click': 'click',
  '"Start certification"': '"Start auth"',
  'Video recording,': 'Video recording,',
  'end after reading the numbers above': 'end after reading the numbers above',
  'There are no suitable merchants':
      'There are no suitable merchants to place a ',
  'pending order': 'pending order',
  'price': 'price',
  'customize': 'customize',
  'Recent Trades': 'Recent Trades',
  'All Trades': 'All Trades',
  'Update Content': 'Update Content',
  'Cruel Rejection': 'Cruel Rejection',
  'Update Now': 'Update Now',
  'Download completed': 'Download completed',
  'Download completed, install now?': 'Download completed, install now?',
  'WiFi environment, only takes 30 seconds':
      'WiFi environment, only takes 30 seconds',
  '温馨提示：如收到款项与交易金额一致，请立即点击“我已确认收款”！切勿相信短信到账通知，请以官方app或网银实时到账为准！':
      'Warm reminder: If the payment received is consistent with the transaction amount, please click "I have confirmed the payment" immediately! Do not believe the SMS notification of account arrival, please refer to the official app or online banking for real-time account arrival!',
  'simple': 'simple',
  'One key exchange': 'One key exchange',
  'The world of digital assets comes and goes freely':
      'The world of digital assets comes and goes freely',
  'security': 'security',
  'Multiple protections': 'Multiple protections',
  'We will protect your digital assets': 'We will protect your digital assets',
  'save worry': 'save worry',
  '24-hour customer service': '24-hour customer service',
  'Everything for you to trade smoothly':
      'Everything for you to trade smoothly',
  'start immediately': 'start immediately',
  'Reminder again: Dear user, we will not call or send text messages to urge you to release your funds before you have received the payment. Please refer to the actual receipt on the bank app for order processing.':
      'Reminder again: Dear user, we will not call or send text messages to urge you to release your funds before you have received the payment. Please refer to the actual receipt on the bank app for order processing.',
  'Know risks and prevent fraud': 'Know risks and prevent fraud',
  'Payment is very simple': 'Payment is very simple',
  'explain': 'explain',
  '1. After selecting the type of pending order, please enter the buying and selling amount according to the requirements, with the lowest highest buying value per order. 2. You can choose to terminate the pending order midway, and the remaining unsold amount will be returned to your account When posting a sell order, please pay attention to whether the wallet balance is sufficient to support the amount of the pending order If the transaction is not completed, the amount of the sell order will be returned to the remaining quantity of the current pending order. If the sell order is successfully published, the amount sold will be temporarily frozen, and terminating the pending order can unfreeze it After successful publication, please pay attention to the system message and take timely action. If the timeout occurs, the order will be automatically cancelled During the transaction process, please check the fund collection status of the receiving account to prevent scammers':
      '1. After selecting the type of pending order, please enter the buying and selling amount according to the requirements, with the lowest highest buying value per order. \n2. You can choose to terminate the pending order midway, and the remaining unsold amount will be returned to your account When posting a sell order, please pay attention to whether the wallet balance is sufficient to support the amount of the pending order If the transaction is not completed, the amount of the sell order will be returned to the remaining quantity of the current pending order. If the sell order is successfully published, the amount sold will be temporarily frozen, and terminating the pending order can unfreeze it After successful publication, please pay attention to the system message and take timely action. If the timeout occurs, the order will be automatically cancelled During the transaction process, please check the fund collection status of the receiving account to prevent scammers',
  'Please choose': 'Please choose',
  'Types of pending orders to be published':
      'Types of pending orders to be published',
  'Sell order': 'Sell order',
  'Buy order': 'Buy order',
  'release': 'release',
  'Please select': 'Please select',
  'Register an account': 'Register an account',
  'Please set up your payment password': 'Please set up your payment password',
  'Payment password': 'Payment password',
  '请输入手机号和验证码完成重置':
      'Please enter your phone number and verification code to complete the reset',
  '我的资产': 'My assets',
  '资金明细': 'Financial details',
  '钱包': 'wallet',
  '详情': 'details',
  '消息': 'message',
  '系统通知': 'System notification',
  '语言切换': 'Language switching',
  '账号管理': 'account management',
  '账户中心': 'Account Center',
  '登录账号': 'Login Account',
  '用户头像': 'head portrait',
  '用户昵称': 'nickname',
  '原密码': 'Original password',
  '设置新密码': 'New password',
  '确认新密码': 'Confirm new password',
  '请输入': 'Please enter',
  '找回支付密码': 'Retrieve payment password',
  '请认真核对收款信息，并确保不要泄露，若因账户信息泄露导致交易异常，平台概不负责。':
      'Please carefully verify the payment information and ensure that it is not disclosed. The platform is not responsible for any abnormal transactions caused by account information leakage.',
  '账户名': 'Account Name',
  '账户号': 'Account number',
  '请输入账户名': 'Please enter the account name',
  '支付状态': 'Payment status',
  '账户类型': 'Account type',
  '账户信息': 'Account information',
  '点击这里上传支付二维码你可以用这个二维码出售或者购买RSO':
      'Click here to upload the payment QR code. You can use this QR code to sell or purchase RSO',
  '添加支付账号': 'Add payment account',
  '上传支付二维码': 'Upload payment QR code',
  '收款人头像': 'Payee portrait',
  '收款人昵称': 'Payee nickname',
  '卖家': 'seller',
  '发布': 'release',
  '审核失败': 'Audit failed',
  '请核查身份信息是否有误并重新提交':
      'Please verify if the identity information is incorrect and resubmit',
  '审核通过': 'Approved by review',
  '实名认证通过开通交易权限':
      'Real name authentication has been activated to grant transaction permissions',
  '返回交易市场': 'Return to the trading market',
  '请先完善信息': 'Please complete the information first',
  '反面': 'the other side',
  '人像': 'positive',
  '审核中': 'in review',
  '已成功发布一个购买单可点击': 'A purchase order has been successfully released. Click',
  '查询': 'query',
  '买家': 'Buyers',
  '奖励说明': 'Reward Description',
  '邀请用户注册并进行首次充值当首次充值金额满一定的rso时邀请人可额外获得rso的奖励':
      'Invite users to register and make their first recharge. When the initial recharge amount reaches a certain RSO, the inviter can receive additional RSO rewards',
  '发布挂单': 'Publish pending orders',
  '转账信息': 'Transfer information',
  '输入或粘贴收款地址': 'Enter or paste the payment address',
  '实际到达': 'Actual arrival',
  '昨天': 'yesterday',
  '刚刚': 'just',
  '点击': 'click',
  '选择': 'choice',
  '发布出售': 'Publish for sale',
  '出售信息': 'Selling information',
  '销售量': 'sales volume',
  '请输入销售金额': 'Please enter the sales amount',
  '单个销售上限': 'Single sales limit',
  '单个销售下限': 'Single sales lower limit',
  '支付金额必须输入': 'The payment amount must be entered',
  '否则订单支付无效': 'Otherwise, the order payment will be invalid',
  '若资金未到账，请': 'If the funds have not been received, please',
  '请手持身份证证件和头部进行实名认证':
      'Please hold your ID card and head for real name authentication',

  '未认证': 'No auth',
  '已认证': 'Certified',

  '上传身份证正面': 'Upload portrait page',
  '上传身份证反面': 'Upload national emblem page',
  '输入真实姓名和身份证号': 'Enter your real name and ID number number',
  '确认完成': 'Confirm completion',

  '视频认证': 'Video authentication',
  '录制视频，朗读屏幕上的数字': 'Record a video and read the numbers on the screen aloud',
  '时长不超过5秒': 'Duration not exceeding 5 seconds',
  '上传视频': 'Upload video',
  '上传录制好的视频，完成验证': 'Upload the recorded video and complete verification',

  '您可经由APP首页的': 'You can access the',
  '进入': 'enter',
  '添加': 'Add',
  '支付宝、微信、银行卡': '',
  '进行下一步': 'Proceed to the next step',
  '填写卡号等个人信息': 'Fill in the card number and other personal information',
  '按钮，完成添加': 'button to finish adding',
  '添加收付款账户': 'Add payment and receipt account',

  '我要卖': 'I want to sell',
  '功能出售': 'Function for sale',
  '选择您想卖出的订单，然后点击': 'Select the order you want to sell and click',
  '选择支付方式，输入卖出数量，然后点击':
      'Select payment method, enter the selling quantity, and then click',
  '按钮': 'button',

  '创建购买订单成功，等待买家确认订单【如买家':
      'Successfully created purchase order, waiting for buyer confirmation of order',

  '5分钟之内': 'Within 5 minutes',

  '没有确定】，该订单': 'not confirmed, this order',

  '功能购买': 'function purchase',

  '我要买': 'I would like to buy it',
  '功能进入': 'function entry',
  '在买币/卖币页面点击': 'Click on the buy/sell coin page',
  '挂单': 'order',
  '进入发布挂单': 'Enter to publish pending orders',
  '在挂单中可选择': 'choose from the pending orders',
  '卖出单': 'sell order',
  '或': 'or',
  '买入单': 'buy order',
  '输入出售或购买的金额数量，单词购买或出售上限以及下限。':
      'Enter the amount and quantity for sale or purchase, as well as the upper and lower limits for word purchase or sale.',
  '选择首付款渠道，并点击': 'Select the payment channel and click',
  '确认发布': 'Confirm release',
  '按钮，发布成功后，可点击跳转':
      'after the button is successfully published, you can click to jump to it',
  '进行查看': 'view it',

  '功能进行充值': 'Function for recharging',
  '选择存款充值通道,输入充值金额,点击':
      'Select the deposit recharge channel, enter the recharge amount, and click',
  '确认充值信息，确认后可进入':
      'Confirm the recharge information and enter after confirmation',
  '在详情中，可在充值明细页面进行查看':
      'In the details, you can view it on the recharge details page',

  '选择您想购买的订单，然后点击': 'Select the order you want to purchase, and click',
  '选择支付方式，输入购买数量，然后点击':
      'Select the payment method, enter the purchase quantity, and then click',
  '创建购买订单成功，等待卖家确认订单【如卖家':
      'The purchase order has been successfully created and is awaiting confirmation from the seller [e.g., the seller',
  '接收': 'receive',
  '实时汇率': 'Real time exchange rate',
  '此地址仅支持与Gopay相关的资产': 'This address supports assets related to Gopay',
  '接收地址': 'Receiving address',
  '复制': 'copy',
  '未绑定收款方式，去绑定？': 'Unbound payment method, go bind it?',
  '立即绑定': 'Bind Now',

  '不再提示': 'No prompts',
  '新密码不能为空': 'The new password cannot be empty',
  '确认密码不能为空': 'Confirm password cannot be empty',
  '两次密码输入不一致': 'The two password inputs are inconsistent',
  '验证码不能为空': 'The verification code cannot be empty',
  'loading': 'loading',
  '加入我们': 'Join Us',
  "支付已关闭": "Payment has been closed"
};
