Map<String, String> zh_CN = {
  '可用余额': '可用余额',
  '冻结中': '冻结中',
  '交易中': '交易中',
  '卖币': '卖币',
  '买币': '买币',
  '收款账户': '收款账户',
  '订单中心': '订单中心',
  '账单记录': '账单记录',
  '我的团队': '我的团队',
  '帮助中心': '帮助中心',
  '代币充值': '代币充值',
  '热门币种': '热门币种',
  '上升': '上升',
  '下降': '下降',
  '首页': '首页',
  '我的': '我的',
  '发布': '发布',
  'Dear user: Thank you for using Gopay wallet. Please follow our working hours: Monday to Sunday AM10:30-PM10:30':
      'Dear user: Thank you for using Gopay wallet. Please follow our working hours: Monday to Sunday AM10:30-PM10:30',
  '合作': '合作',
  '交易下限': '交易下限',
  '交易上限': '交易上限',
  '支付方式': '支付方式',
  '1万': '1万',
  '10万': '10万',
  '20万': '20万',
  '例如 100': '例如 100',
  '重置': '重置',
  '确认': '确认',
  '成单量': '成单量',
  '成单率': '成单率',
  '分钟': '分钟',
  '剩余金额 ': '剩余金额 ',
  '限额 ': '限额 ',
  '购买': '购买',
  '出售': '出售',
  '确认订单': '确认订单',
  '付款时限': '付款时限',
  '限制额度': '限制额度',
  '交易方式': '交易方式',
  '请输入金额': '请输入金额',
  '金额': '金额',
  '总额': '总额',
  '买家留言': '买家留言',
  '卖家留言': '卖家留言',
  '交易须知': '交易须知',
  '付款信息': '付款信息',
  '未识别': '未识别',
  'tradeTerms':
      '1.当订单生成后请在10分钟内完成转账并上传交易凭证\n2.交易时请用以绑定的支付方式去支付，如付款信息不符卖家有权不放行\n3.请不要恶意发起购买订单，查证属实后永久封号处理。\n4.如果遇到无法支付，交易纠纷，亲点击上方客服按钮。',
  '温馨提示': '温馨提示',
  '为保证资金安全，我们将随机小数点后两位，请按照具体金额进行支付': '为保证资金安全，我们将随机小数点后两位，请按照具体金额进行支付',

  '输入密码支付': '输入密码支付',
  '为了安全起见，请输入您的交易密码以继续交易': '为了安全起见，请输入您的交易密码以继续交易',
  '输入密码': '输入密码',
  '等待卖家确认': '等待卖家确认',
  '已通知，等待卖家确认订单': '已通知，等待卖家确认订单',
  '等待买家确认': '等待买家确认',
  '待付款': '待付款',
  '待确认收款': '待确认收款',
  '剩余时间 ': '剩余时间 ',
  '订单号': '订单号',
  '查看详情': '查看详情',
  '总金额': '总金额',
  '备注码': '备注码',
  '卖家信息': '卖家信息',
  '取消订单': '取消订单',
  '通知卖家': '通知卖家',
  '通知买家': '通知买家',
  '催单': '催单',
  '收款方式': '收款方式',
  '收款二维码': '收款二维码',
  '有过合作用户': '有过合作用户',
  '收款通道': '收款通道',
  '添加收款方式': '添加收款方式',
  '异常': '异常',
  '开启': '开启',
  '关闭': '关闭',
  '账号': '账号',
  '姓名': '姓名',
  '银行卡号': '银行卡号',
  '收款地址类型': '收款地址类型',
  '收款地址': '收款地址',
  '收款码': '收款码',
  '您暂时无法接受订单，请先添加一个收款方式': '您暂时无法接受订单，请先添加一个收款方式',
  '删除': '删除',
  '收款状态': '收款状态',
  '钱包地址协议': '钱包地址协议',
  '请选择钱包地址协议': '请选择钱包地址协议',
  '钱包地址': '钱包地址',
  '请输入钱包地址': '请输入钱包地址',
  '请输入账号': '请输入账号',
  '开户行': '开户行',
  '请输入开户行 (XXX银行XXX市XXX支行)': '请输入开户行 (XXX银行XXX市XXX支行)',
  '收款人姓名': '收款人姓名',
  '请输入收款人姓名': '请输入收款人姓名',
  '上传二维码': '上传二维码',
  '请选择包含二维码图片': '请选择包含二维码图片',
  '温馨提醒:': '温馨提醒:',
  '点击此处上传您的': '点击此处上传您的',
  '收付款二维码，您可以使用此二维码进行买卖': '收付款二维码，您可以使用此二维码进行买卖',
  '保存': '保存',
  '发布选择': '发布选择',
  '我的挂单': '我的挂单',
  '我的订单': 'My order',
  '订单管理': '订单管理',
  '挂单记录': '挂单记录',
  '全部': '全部',
  '买入': '买入',
  '卖出': '卖出',
  '已完成': '已完成',
  '已取消': '已取消',
  '已终止': '已终止',
  '确认终止挂单吗?': '确认终止挂单吗?',
  '终止挂单': '终止挂单',
  '收款类型': '收款类型',
  '数量': '数量',
  '剩余数量': '剩余数量',
  '单次购买上限': '单次购买上限',
  '单次购买下限': '单次购买下限',
  '申诉中': '申诉中',
  '订单已取消': '订单已取消',
  '等待卖家确认收款': '等待卖家确认收款',
  '此卖家95%订单会在7:00处理': '此卖家95%订单会在7:00处理',
  '我的购买': '我的购买',
  '我的出售': '我的出售',
  '等待买家确认付款': '等待买家确认付款',
  '收款信息': '收款信息',
  '如收到款项与交易金额一致，请立即点击我已确认收款， 切勿相信短信到账提示，请已官方App或网银实时为主！':
      '如收到款项与交易金额一致，请立即点击我已确认收款， 切勿相信短信到账提示，请已官方App或网银实时为主！',
  '此卖家95%的订单将会在7分钟内完成': '此卖家95%的订单将会在7分钟内完成',
  '卖家收款方式': '卖家收款方式',
  '付款凭证': '付款凭证',
  '请确认已收到款': '请确认已收到款',
  '将确认收款': '将确认收款',
  '登录下方收款账号确认收款到账': '登录下方收款账号确认收款到账',
  '如若未收到款或收款金额与交易金额不符，请在倒计时结束前点击未收到款！': 'zh如若未收到款或收款金额与交易金额不符，请在倒计时结束前点击未收到款！',
  '未收到款': '未收到款',
  '我已确认收款': '我已确认收款',
  '买入成功': '买入成功',
  '卖出成功': '卖出成功',
  '创建时间': '创建时间',
  '完成': '完成',
  '您已成功购买 num coinName': '您已成功购买:num:coinName',
  '您已成功出售 num coinName': '您已出售购买:num:coinName',
  '订单信息': '订单信息',
  '卖家昵称': '卖家昵称',
  '买家昵称': '买家昵称',
  '进行中': '进行中',
  '请选择日期区间': '请选择日期区间',
  '取消': '取消',
  '确定': '确定',
  '选择时间': '选择时间',
  '记录为空': '记录为空',
  '余额': '余额',
  '时间': '时间',
  '今日收益': '今日收益',
  '昨日收益': '昨日收益',
  '累计收益': '累计收益',
  '直接邀请': '直接邀请',
  '间接邀请': '间接邀请',
  '我的代理': '我的代理',
  '转账': '转账',
  '直邀': '直邀',
  '间邀': '间邀',
  '今日贡献': '今日贡献',
  '昨日贡献': '昨日贡献',
  '累计贡献': '累计贡献',
  '佣金金额': '佣金金额',
  '团队用户': '团队用户',
  '代理管理': '代理管理',
  '佣金比例': '佣金比例',
  '代付佣金比例': '代付佣金比例',
  '代收佣金比例': '代收佣金比例',
  '修改佣金比例': '修改佣金比例',
  '修改后立即生效，只可更改一次。请谨慎处理。': '修改后立即生效，只可更改一次。请谨慎处理。',
  '请输入佣金比例': '请输入佣金比例',
  '充值': '充值',
  '充值明细': '充值明细',
  '选择公链协议': '选择公链协议',
  '区块链浏览器': '区块链浏览器',
  'chargeTip': '当前地址只能充入USDT，且主网公链:chainType协议，不能充值其他币种，否则会丢失且无法追回。',
  '提交': '提交',
  '加载地址失败': '加载地址失败',
  '预估': '预估',
  '您的购买地址': '您的购买地址',
  '复制成功': '复制成功',
  '需支付金额（USDT）': '需支付金额（USDT）',
  '保存成功': '保存成功',
  '分享': '分享',
  '充值金额': '充值金额',
  '充值详情': '充值详情',
  '您正在充值': '您正在充值',
  '您已经成功充值': '您已经成功充值',
  '充值时间': '充值时间',
  '充币公链协议': '充币公链协议',
  '实际支付': '实际支付',
  '交易HASH': '交易HASH',
  '充值失败': '充值失败',
  '失败': '失败',
  '查看全部': '查看全部',
  '支付': '支付',
  '未知': '未知',
  '购买金额': '购买金额',
  '请输入购买金额': '请输入购买金额',
  '请输入最大金额': '请输入最大金额',
  '备注': '备注',
  '请输入您要留下的备注': '请输入您要留下的备注',
  '付款类型': '付款类型',
  '您确认要发布该广告嘛': '您确认要发布该广告嘛',
  '发布订单': '发布订单',
  '收款渠道': '收款渠道',
  '付款渠道': '付款渠道',
  '确认渠道': '确认渠道',
  '发布卖出': '发布卖出',
  '卖出金额': '卖出金额',
  '请输入卖出金额': '请输入卖出金额',
  '单次卖出上限': '单次卖出上限',
  '单次卖出下限': '单次卖出下限',
  '请输入最小金额': '请输入最小金额',
  '确定退出': '确定退出',
  '您确定要退出登录吗?': '您确定要退出登录吗?',
  '退出': '退出',
  '设置': '设置',
  '账号绑定': '账号绑定',
  '语言': '语言',
  '提现': '提现',
  '密码与安全': '密码与安全',
  '交易密码': '交易密码',
  '登录密码': '登录密码',
  '分享有礼': '分享有礼',
  '用户须知': '用户须知',
  '邀请码': '邀请码',
  '邀请码（选填）': '邀请码（选填）',
  '当前版本': '当前版本',
  '个人信息': '个人信息',
  '设置用户昵称': '设置用户昵称',
  '请输入你的昵称': '请输入你的昵称',
  '手机号绑定': '手机号绑定',
  '未绑定': '未绑定',
  '邮箱绑定': '邮箱绑定',
  '输入您的手机号': '输入您的手机号',
  '输入您的邮箱': '输入您的邮箱',
  '验证码': '验证码',
  '获取验证码': '获取验证码',
  '重新获取': '重新获取',
  '请输入验证码': '请输入验证码',
  '明细': '明细',
  '请输入收款地址': '请输入收款地址',
  '提现金额': '提现金额',
  '请输入提现金额': '请输入提现金额',
  '手续费': '手续费',
  '将收到': '将收到',
  '您确认要提现吗': '您确认要提现吗',
  '确定提现': '确定提现',
  '请输入交易密码': '请输入交易密码',
  '提现明细': '提现明细',
  '地址': '地址',
  '状态': '状态',
  '未处理': '未处理',
  '已通过': '已通过',
  '已拒绝': '已拒绝',
  '请输入当前密码': '请输入当前密码',
  '密码输入': '密码输入',
  '请输入新密码': '请输入新密码',
  '再次输入新密码': '再次输入新密码',
  '您想要修改密码吗？': "您想要修改密码吗？",
  '保存图片': '保存图片',
  '您的收款地址:': '您的收款地址:',
  '转账记录': '转账记录',
  '您的转账地址': '您的转账地址',
  '输入或粘贴地址': '输入或粘贴地址',
  '转账金额': '转账金额',
  '实际到账': '实际到账',
  '记录': '记录',
  '收款': '收款',
  '转账地址': '转账地址',
  '需要操作': '需要操作',
  '待确认': '待确认',
  '确认收款': '确认收款',
  '如果你未收到订单的现金。请不要确认订单，否则资金损失，我们不予负责': '如果你未收到订单的现金。请不要确认订单，否则资金损失，我们不予负责',
  'uploading': 'uploading',
  '欢迎回来': 'welcome to',
  'welcome': 'welcome',
  'to': 'to',
  'Log in to your account': 'Log in to your account',
  '创建账户': '创建账户',
  '已有账户': '已有账户',
  '接收验证码': '接收验证码',
  '密码登录': '密码登录',
  '没有帐号？': '没有帐号？',
  '前去注册': '前去注册',
  '找回方式': '找回方式',
  '邮箱找回': '邮箱找回',
  '手机号找回': '手机号找回',
  '请输入帐号': '请输入帐号',
  '请输入您的密码': '请输入您的密码',
  '二次确认密码': '二次确认密码',
  '再次输入密码': '再次输入密码',
  '请输入正确的手机号或邮箱': '请输入正确的手机号或邮箱',
  '请输入收到的验证码': '请输入收到的验证码',
  '请输入设置的密码': '请输入设置的密码',
  '请输入确认密码': '请输入确认密码',
  '两次输入的密码不一致，请重新输入': '两次输入的密码不一致，请重新输入',
  '让我们开始吧！': '让我们开始吧！',
  '现在就注册!': '现在就注册!',
  '输入用户昵称': '输入用户昵称',
  '已有帐户？': '已有帐户？',
  '身份认证已通过': '身份认证已通过',
  '您的收款二维码': '您的收款二维码',
  '确认收款吗?': '确认收款吗?',
  '发布成功': '发布成功',
  '成功': '成功',
  '添加成功': '添加成功',
  '修改成功': '修改成功',
  '添加付款凭证': '添加付款凭证',
  '添加付款凭证录屏（可选）': '添加付款凭证录屏（可选）',
  '请添加付款凭证': '请添加付款凭证',
  '请选择付款类型': '请选择付款类型',

  '总价': '总价',
  '申诉': '申诉',
  '撤销申诉': '撤销申诉',
  '申诉原因': '申诉原因',
  '申诉内容': '申诉内容',
  '输入申诉内容': '输入申诉内容',
  '申诉内容(可选择)': '申诉内容(可选择)',
  '添加交易截图': '添加交易截图',
  '添加交易录屏 (可选)': '添加交易录屏 (可选)',
  '确定申诉': '确定申诉',
  '请选择申诉原因': '请选择申诉原因',
  '确定取消吗': '确定取消吗',
  '实名认证': '实名认证',
  '添加收付款': '添加收付款',

  '第一步：进入实名认证': '第一步：进入实名认证',
  '第二步：输入身份证信息': '第二步：输入身份证信息',
  '第一步：进入市场购买': '第一步：进入市场购买',

  '在首页，点击购买按钮，进入市场': '在首页，点击购买按钮，进入市场',
  '第二步：市场购买': '第二步：市场购买',
  '选择买家后，输入需要购买金额并选择付款方式': '选择买家后，输入需要购买金额并选择付款方式',
  '第三步：等待卖家确认': '第三步：等待卖家确认',

  '第一步：进入市场出售': '第一步：进入市场出售',
  '在首页，点击出售按钮，进入市场': '在首页，点击出售按钮，进入市场',
  '第二步：市场出售': '第二步：市场出售',
  '选择买家后，输入需要出售金额并选择付款方式': '选择买家后，输入需要出售金额并选择付款方式',
  '第三步：等待买家确认': '第三步：等待买家确认',
  '验证码验证错误': '验证码验证错误',
  '尚未绑定手机号': '尚未绑定手机号',

  '请输入两次密码不一致，请重新输入': '请输入两次密码不一致，请重新输入',
  '请输入您的确认密码': '请输入您的确认密码',
  '请输入您的名字': '请输入您的名字',
  '已通知，等待买家确认订单': '已通知，等待买家确认订单',

  '请确认支付密码': '请确认支付密码',
  '支付密码两次设置不一样': '支付密码两次设置不一样',
  '请输入支付密码': '请输入支付密码',
  '请输入转账金额': '请输入转账金额',

  '交易': '交易',
  '商户': '商户',
  '承兑': '承兑',

  '当前汇率': '当前汇率',

  //我的
  '身份认证': '身份认证',
  '收款管理': '收款管理',
  '历史订单': '历史订单',
  '谷歌验证': '谷歌验证',
  '关于我们': '关于我们',
  '在线客服': '在线客服',
  //交易
  '更多': '更多',
  '匹配中': '匹配中',

  '暂无订单信息～': '暂无订单信息～',
  //other
  '通知': '通知',
  '当前通话已被加密': '当前通话已被加密',
  '客服': '客服',
  '相册': '相册',
  '公链协议（即网络协议）': '公链协议（即网络协议）',
  '请输入您要购买的:coin数量': '请输入您要购买的:coin数量',
  '需支付': '需支付',
  '购买二维码': ':coinName购买二维码',
  '保存二维码': '保存二维码',
  '请严格按照以上金额进行转账, 否则如果无法到账, 平台概不负责': '请严格按照以上金额进行转账, 否则如果无法到账, 平台概不负责',
  '购买明细': '购买明细',

  '支付USDT': '支付USDT',
  'coinName购买': ':coinName购买',
  '收益记录': '收益记录',
  '今日': '今日',
  '昨日': '昨日',
  '进行中订单': '进行中订单',
  '代收金额': '代收金额',
  '代付金额': '代付金额',
  '总收益': '总收益',
  '收益明细': '收益明细',
  '请选择日期': '请选择日期',
  '收入': '收入',
  '原订单号': '原订单号',
  'shareTip1': '分享新用户完成:limit:coinName币交易',
  'shareTip2': '即可获得 :reward:coinName币 的奖励',
  '昵称': '昵称',
  '修改登录密码': '修改登录密码',
  '邮箱': '邮箱',
  '未设置': '未设置',
  '手机号': '手机号',
  '资金密码': '资金密码',
  '修改资金密码': '修改资金密码',
  '退出登录': '退出登录',
  '确认退出吗?': '确认退出吗?',
  '请输入昵称': '请输入昵称',
  '5-12位字母或数字，请勿使用特殊符号': '5-12位字母或数字，请勿使用特殊符号',
  '旧密码': '旧密码',
  '请输入旧密码': '请输入旧密码',
  '密码': '密码',
  '请输入密码': '请输入密码',
  '确认密码': '确认密码',
  '开启手机验证': '开启手机验证',
  '开启邮箱验证': '开启邮箱验证',
  '为您的账户提供更安全的保护。': '为您的账户提供更安全的保护。',
  '请输入手机号': '请输入手机号',
  '请输入邮箱号': '请输入邮箱号',
  '下一步': '下一步',
  '请输入正确的手机号码': '请输入正确的手机号码',
  '请输入正确的邮箱': '请输入正确的邮箱',
  '请输入发送至手机号 phone的6位验证码': '请输入发送至手机号 :phone的6位验证码',
  '重新获取(seconds秒)': '重新获取(:seconds秒)',
  '手机': '手机',
  '请输入6位纯数字密码': '请输入6位纯数字密码',
  '银行卡': '银行卡',
  '支付宝': '支付宝',
  '微信': '微信',

  '微信账号': '微信账号',
  '请输入支付宝账号': '请输入支付宝账号',
  '请输入微信账号': '请输入微信账号',
  '请输入银行卡号': '请输入银行卡号',
  '每日最大接单金': '每日最大接单金',
  '返回': '返回',
  '全选': '全选',

  '卖家收款二维码': '卖家收款二维码',

  '我的余额': '我的余额',
  '代理佣金': '代理佣金',

  '修改': '修改',
  'error': 'error',

  '收款记录': '收款记录',
  '请在手机上安装谷歌身份验证器': '请在手机上安装谷歌身份验证器',
  '复制密钥': '复制密钥',
  '二维码': '二维码',
  '开启谷歌验证': '开启谷歌验证',
  '请输入6位验证码': '请输入6位验证码',
  '谷歌验证身份': '谷歌验证身份',
  '验证身份': '验证身份',
  '请选择您要成为的身份': '请选择您要成为的身份',
  '自动接单': '自动接单',
  '去完成': '去完成',
  '商家': '商家',
  '发布广告': '发布广告',
  'Please complete': 'Please complete',
  "'authentication'": "'authentication'",
  'authentication': 'authentication',
  'video auth': 'video auth',
  'Upload ID card photo': 'Upload ID card photo',
  'ID card is used to bind: transaction info':
      'ID card is used to bind: transaction info',
  'auth': 'auth',
  'Identity information': 'Identity information',
  'Real name': 'Real name',
  'ID Number': 'ID Number',
  'standard': 'standard',
  'defect': 'defect',
  'vague': 'vague',
  'Strong light': 'Strong light',
  'Start certification': 'Start auth',
  'End certification': 'End auth',
  'light': 'light',
  'face': 'face',
  'No glasses': 'No glasses',
  'No hat': 'No hat',
  'click': 'click',
  'Video recording,': 'Video recording,',
  'end after reading the numbers above': 'end after reading the numbers above',
  '"Start certification"': '"Start auth"',
  'There are no suitable merchants':
      'There are no suitable merchants to place a ',
  'pending order': 'pending order',
  'price': 'price',
  '认证': '认证',
  '商户名称': '商户名称',
  '请输入您的商户名称': '请输入您的商户名称',
  '请输入您的昵称': '请输入您的昵称',
  '请输入您的联系方式': '请输入您的联系方式',
  '地址链接': '地址链接',
  '请输入您的地址链接': '请输入您的地址链接',
  '登录': '登录',
  '注册': '注册',
  '忘记密码': '忘记密码',
  '请输入邮箱': '请输入邮箱',
  '手机号码': '手机号码',
  '请选择国家/地区': '请选择国家/地区',
  '切换验证码登录': '切换验证码登录',
  '切换密码登录': '切换密码登录',
  '“国家/地区”、“代码”或“拨号代码”': '“国家/地区”、“代码”或“拨号代码”',
  '请输入邀请码': '请输入邀请码',
  '已有账号，去登录': '已有账号，去登录',
  '重置密码': '重置密码',
  '确认重置': '确认重置',
  '发布买入': '发布买入',
  '今日购买上限': '今日购买上限',
  '今日卖出上限': '今日卖出上限',
  '请输入购买数量': '请输入购买数量',
  '保存配置': '保存配置',
  '停止接单': '停止接单',
  '开启接单': '开启接单',
  '卖出数量': '卖出数量',
  '请输入卖出数量': '请输入卖出数量',
  '您确认要出售吗': '您确认要出售吗?',
  '确定出售': '确定出售',
  '出售明细': '出售明细',
  '预计将在time打款': '预计将在 :time 打款',

  '交易记录': '交易记录',
  '再按一次退出应用': '再按一次退出应用',
  '提交成功!': '提交成功!',
  '联系客服': '联系客服',
  '单价': '单价',

  '银行借记卡': '银行借记卡',
  '按金额卖出': '按金额卖出',
  '按数量卖出': '按数量卖出',
  '按金额购买': '按金额购买',
  '按数量购买': '按数量购买',
  '交易条款': '交易条款',

  '1.如果您已经付款给卖家，请勿取消订单': '1.如果您已经付款给卖家，请勿取消订单',
  '2.如因系统超时订单取消，买家将被记责（完成率受影响）。': '2.如因系统超时订单取消，买家将被记责（完成率受影响）。',
  '3.如果卖家在15分钟内没有回复聊天，则买家无责，您的成单率将不受影响，一天内只能3次无责取消。':
      '3.如果卖家在15分钟内没有回复聊天，则买家无责，您的成单率将不受影响，一天内只能3次无责取消。',
  '4.一天内您最多只能3次有责取消，否则，您的账户将被暂停，并且不能再同一天内再下订单。':
      '4.一天内您最多只能3次有责取消，否则，您的账户将被暂停，并且不能再同一天内再下订单。',
  '确认取消': '确认取消',
  '请等待客服处理': '请等待客服处理',
  '收款账号': '收款账号',

  '充值至您的账户': '充值至您的账户',
  '已经成功出售': '已经成功出售',

  '链类型': '链类型',
  '请确认已收到付款': '请确认已收到付款',
  '后将自动确认收款': '后将自动确认收款',
  '登录您下方的收款账户，确认买家的付款已到账。': '登录您下方的收款账户，确认买家的付款已到账。',
  '买家实名': '买家实名',
  '重要提示：如果未收到款或者收到款项与交易金额不符，请在倒计时结束前点击“未收到款”！':
      '重要提示：如果未收到款或者收到款项与交易金额不符，请在倒计时结束前点击“未收到款”！',
  '请使用paymentType支付转账': '请使用:paymentType支付转账',
  '资金将划转至您的账户': '资金将划转至您的账户',
  '订单即将生成': '订单即将生成',
  '预计将在': '预计将在',
  '自动取消': '自动取消',
  '我已付款': '我已付款',
  '等待买家付款': '等待买家付款',
  '付款剩余时间：': '付款剩余时间：',
  '异常原因': '异常原因',
  '无法付款': '无法付款',
  '温馨提示：如收到款项与交易金额一致，请立即点击“我已确认收款”！切勿相信短信到账通知，请以官方app或网银实时到账为准！':
      '温馨提示：如收到款项与交易金额一致，请立即点击“我已确认收款”！切勿相信短信到账通知，请以官方app或网银实时到账为准！',

  '凌晨': '凌晨',
  '早晨': '早晨',
  '上午': '上午',
  '中午': '中午',
  '下午': '下午',
  '傍晚': '傍晚',
  '晚上': '晚上',

  '年': '年',
  '月': '月',
  '日': '日',
  'simple': 'simple',
  'customize': 'customize',
  'Recent Trades': 'Recent Trades',
  'All Trades': 'All Trades',
  'Update Content': 'Update Content',
  'Cruel Rejection': 'Cruel Rejection',
  'One key exchange': 'One key exchange',
  'Update Now': 'Update Now',
  'Download completed': 'Download completed',
  'Download completed, install now?': 'Download completed, install now?',
  'WiFi environment, only takes 30 seconds':
      'WiFi environment, only takes 30 seconds',
  'The world of digital assets comes and goes freely':
      'The world of digital assets comes and goes freely',
  'security': 'security',
  'Multiple protections': 'Multiple protections',
  'We will protect your digital assets': 'We will protect your digital assets',
  'save worry': 'save worry',
  '24-hour customer service': '24-hour customer service',
  'Everything for you to trade smoothly':
      'Everything for you to trade smoothly',
  'start immediately': 'start immediately',
  'Reminder again: Dear user, we will not call or send text messages to urge you to release your funds before you have received the payment. Please refer to the actual receipt on the bank app for order processing.':
      'Reminder again: Dear user, we will not call or send text messages to urge you to release your funds before you have received the payment. Please refer to the actual receipt on the bank app for order processing.',
  'Know risks and prevent fraud': 'Know risks and prevent fraud',
  'Payment is very simple': 'Payment is very simple',
  'explain': 'explain',
  '1. After selecting the type of pending order, please enter the buying and selling amount according to the requirements, with the lowest highest buying value per order. 2. You can choose to terminate the pending order midway, and the remaining unsold amount will be returned to your account When posting a sell order, please pay attention to whether the wallet balance is sufficient to support the amount of the pending order If the transaction is not completed, the amount of the sell order will be returned to the remaining quantity of the current pending order. If the sell order is successfully published, the amount sold will be temporarily frozen, and terminating the pending order can unfreeze it After successful publication, please pay attention to the system message and take timely action. If the timeout occurs, the order will be automatically cancelled During the transaction process, please check the fund collection status of the receiving account to prevent scammers':
      'explain',
  'Please choose': 'Please choose',
  'Types of pending orders to be published':
      'Types of pending orders to be published',
  'Sell order': 'Sell order',
  'Buy order': 'Buy order',
  'release': 'release',
  'Please select': 'Please select',
  'Register an account': 'Register an account',
  'Please set up your payment password': 'Please set up your payment password',
  'Payment password': 'Payment password',
  '请输入手机号和验证码完成重置': '请输入手机号和验证码完成重置',
  '我的资产': 'My assets',
  '资金明细': 'Financial details',
  '钱包': 'wallet',
  '详情': 'details',
  '消息': 'message',
  '系统通知': 'System notification',
  '语言切换': 'Language switching',
  '账号管理': 'account management',
  '账户中心': 'Account Center',
  '登录账号': 'Login Account',
  '用户头像': 'head portrait',
  '用户昵称': 'nickname',
  '原密码': 'Original password',
  '设置新密码': 'New password',
  '确认新密码': 'Confirm new password',
  '请输入': 'Please enter',
  '找回支付密码': 'Retrieve payment password',
  '请认真核对收款信息，并确保不要泄露，若因账户信息泄露导致交易异常，平台概不负责。':
      'Please carefully verify the payment information and ensure that it is not disclosed. The platform is not responsible for any abnormal transactions caused by account information leakage.',
  '账户名': 'Account Name',
  '账户号': 'Account number',
  '请输入账户名': 'Please enter the account name',
  '支付状态': 'Payment status',
  '账户类型': 'Account type',
  '账户信息': 'Account information',
  '点击这里上传支付二维码你可以用这个二维码出售或者购买RSO':
      'Click here to upload the payment QR code. You can use this QR code to sell or purchase RSO',
  '添加支付账号': 'Add payment account',
  '上传支付二维码': '上传支付二维码',
  '收款人头像': 'Payee portrait',
  '收款人昵称': 'Payee nickname',
  '卖家': 'seller',
  '审核失败': 'Audit failed',
  '请核查身份信息是否有误并重新提交':
      'Please verify if the identity information is incorrect and resubmit',
  '审核通过': 'Approved by review',
  '实名认证通过开通交易权限':
      'Real name authentication has been activated to grant transaction permissions',
  '返回交易市场': 'Return to the trading market',
  '请先完善信息': 'Please complete the information first',
  '反面': 'the other side',
  '人像': 'positive',
  '审核中': 'in review',
  '已成功发布一个购买单可点击': 'A purchase order has been successfully released. Click',
  '查询': 'query',
  '买家': 'Buyers',
  '奖励说明': 'Reward Description',
  '邀请用户注册并进行首次充值当首次充值金额满一定的rso时邀请人可额外获得rso的奖励':
      'Invite users to register and make their first recharge. When the initial recharge amount reaches a certain RSO, the inviter can receive additional RSO rewards',
  '发布挂单': 'Publish pending orders',
  '转账信息': 'Transfer information',
  '输入或粘贴收款地址': 'Enter or paste the payment address',
  '实际到达': 'Actual arrival',
  '昨天': 'yesterday',
  '刚刚': 'just',
  '点击': 'click',
  '选择': 'choice',
  '发布出售': 'Publish for sale',
  '出售信息': 'Selling information',
  '销售量': 'sales volume',
  '请输入销售金额': 'Please enter the sales amount',
  '单个销售上限': 'Single sales limit',
  '单个销售下限': 'Single sales lower limit',
  '支付金额必须输入': '支付金额必须输入',
  '否则订单支付无效': '否则订单支付无效',
  '若资金未到账，请': '若资金未到账，请',
  '请手持身份证证件和头部进行实名认证': '请手持身份证证件和头部进行实名认证',

  '不再提示': '不再提示',
  '未认证': '未认证',
  '已认证': '已认证',
  '未绑定收款方式，去绑定？': '未绑定收款方式，去绑定？',
  '立即绑定': 'Bind Now',
  '新密码不能为空': '新密码不能为空',
  '确认密码不能为空': '确认密码不能为空',
  '两次密码输入不一致': '两次密码输入不一致',
  '验证码不能为空': '验证码不能为空',
  'loading': 'loading',
  '加入我们': '加入我们',
  '支付已关闭': "支付已关闭"
};
